Date comparison [unreliable]

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -5,6 +5,7 @@ FILTER=""
 COMMAND="list"
 USERNAME=""
 LOGS=""
+CURRENCIES=()
 
 # Parse options
 while [[ $# -gt 0 ]]; do
@@ -27,7 +28,7 @@ while [[ $# -gt 0 ]]; do
             shift 2
         ;;
         -c | --currency )
-            FILTER+=" -c $2"
+            CURRENCIES+=("$2")
             shift 2
         ;;
         -*)
@@ -57,27 +58,41 @@ else
     exit 1
 fi
 
+# Výpis informací
 echo "Filter: $FILTER"
 echo "Command: $COMMAND"
 echo "Username: $USERNAME"
 echo "Logs: $LOGS"
+echo "Currencies: ${CURRENCIES[@]}"
+
+# Ověření, zda je COMMAND platný
+case "$COMMAND" in
+    list | list-currency | status | profit)
+        echo "Command is valid: $COMMAND"
+    ;;
+    *)
+        echo "Error: Invalid command: $COMMAND" >&2
+        exit 1
+    ;;
+esac
+
 
 # Získání data a času ze zadaného filtru
-AFTER_DATETIME=$(echo "$FILTER" | grep -oP '\s-a\s\K[^\s]+')
+AFTER=$(echo "$FILTER" | grep -oP '\s-a\s\K[^\s]+')
 
 # Pokud je zadaný filtr -a, vypíše se získané datum a čas
-if [ -n "$AFTER_DATETIME" ]; then
-    echo "Filtr -a byl zadán s hodnotou: $AFTER_DATETIME"
+if [ -n "$AFTER" ]; then
+    echo "Filtr -a byl zadán s hodnotou: $AFTER"
 else
     echo "Filtr -a nebyl zadán."
 fi
 
 # Získání data a času ze zadaného filtru
-BEFORE_DATETIME=$(echo "$FILTER" | grep -oP '\s-b\s\K[^\s]+')
+BEFORE=$(echo "$FILTER" | grep -oP '\s-b\s\K[^\s]+')
 
 # Pokud je zadaný filtr -b, vypíše se získané datum a čas
-if [ -n "$BEFORE_DATETIME" ]; then
-    echo "Filtr -b byl zadán s hodnotou: $BEFORE_DATETIME"
+if [ -n "$BEFORE" ]; then
+    echo "Filtr -b byl zadán s hodnotou: $BEFORE"
 else
     echo "Filtr -b nebyl zadán."
 fi
@@ -86,14 +101,8 @@ fi
 CURRENCY=$(echo "$FILTER" | grep -oP '\s-c\s\K[^\s]+')
 
 # Pokud je zadaný filtr -a, vypíše se získané datum a čas
-if [ -n "$CURRENCY" ]; then
-    echo "Filtr -c byl zadán s hodnotou: $CURRENCY"
-else
-    echo "Filtr -c nebyl zadán."
-fi
-
-if [ -n "$CURRENCY" ]; then
-    echo "Filtr -c byl zadán s hodnotou: $CURRENCY"
+if [ -n "$CURRENCIES" ]; then
+    echo "Filtr -c byl zadán s hodnotou: $CURRENCIES"
 else
     echo "Filtr -c nebyl zadán."
 fi
@@ -102,9 +111,9 @@ case "$COMMAND" in
     list | list-currency | status | profit)
         case "$COMMAND" in
             list | list-currency)
-                awk -F';' -v cur=$CURRENCY -v com=$COMMAND -v user=$USERNAME \
-                '{if(user==$1)
-                    if(com=="list-currency") print $3 
+                awk -F';' -v bfr=$BEFORE -v afr=$AFTER -v cur=$CURRENCY -v com=$COMMAND -v user=$USERNAME \
+                '{if(user==$1 && (!bfr || bfr < $2) && (!afr || afr > $2))
+                    if(com=="list-currency") print $3
                     else if(cur==$3 || !cur) print}' log.txt | uniq
             ;;
             *)
