version that was submitted.

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -1,4 +1,7 @@
-#!/bin/bash
+#!/bin/sh
+
+# setting locale so that it does produce floats with decimal dot
+export LC_NUMERIC="en_US.UTF-8"
 
 # Default values
 AFTER=""
@@ -11,11 +14,13 @@ CURRENCIES=()
 
 PROFIT=${XTF_PROFIT:-20}
 
-# Parse options
+# going through parse options
 while [[ $# -gt 0 ]]; do
     case "$1" in
         -h | --help )
             echo "Usage: xtf [-h|--help] [FILTR] [PŘÍKAZ] UŽIVATEL LOG [LOG2 [...]]"
+            echo "Extraordinary tool to scam people while they think they actually profit out of it"
+            echo "because it's fun to do. xramas01@2024"
             echo "Options:"
             echo "  -h, --help          Display this help message"
             echo "  -a, --after DATETIME         Filter records after DATETIME"
@@ -23,7 +28,7 @@ while [[ $# -gt 0 ]]; do
             echo "  -c, --currency CURRENCY         Filter records by currency"
             exit 0
         ;;
-        -a | --after )
+        -a | --after ) # adding --after... přepínač? for pretty printing. Same goes for the rest
             AFTER+="$2"
             shift 2
         ;;
@@ -46,7 +51,7 @@ while [[ $# -gt 0 ]]; do
 done
 
 # Extracting the rest of the arguments
-if [ $# -ge 3 ]; then
+if [ $# -ge 2 ]; then
     case "$1" in list | list-currency | status | profit)
         COMMAND=$1
         USERNAME=$2
@@ -63,38 +68,44 @@ else
     exit 1
 fi
 
-
+# preventing duplicate entries to mess up the program (this really happens :( )
+PROCESSED=()
 for i in $LOGS; do
-    if [[ -f "$i" && "$i" == *.gz ]]; then
-        RECORDS+=`gunzip -c "$i"`
-    else
-        RECORDS+=`cat "$i"`
+    if [[ ! ${PROCESSED[@]} =~ $i ]]; then
+        if [[ -f "$i" && "$i" == *.gz ]]; then
+            RECORDS+=`gunzip -c "$i"`
+        else
+            RECORDS+=`cat "$i"`
+        fi
+        PROCESSED+=($i)
+        RECORDS+="\n"
     fi
-    RECORDS+="\n"
 done
 
+# performs second check whether correct command has been loaded (don't think that's necessary)
 case "$COMMAND" in
     list | list-currency | status | profit)
+        # at this point I am quite worried whether this all logic was supposed to be written in awk
         echo -e "$RECORDS" | awk -F';' -v bfr="$BEFORE" -v afr="$AFTER" -v curs="${CURRENCIES[*]}" -v com=$COMMAND -v user=$USERNAME -v prof=$PROFIT \
-        'function convdate(date){
+        'function convdate(date){ # converts dates into numbers for a comparison reasons afterward
             if (date ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/) {
                 gsub(/[-]/, "", date);
-                date = date "000000";  # Přidej výchozí čas (půlnoc)
+                date = date "000000";  # appends zeros if HH:MM:SS was not specified (probably will not happen, but I was lazy to write the entire thing when testing)
             }
-            # Pokud je formát YYYY-MM-DD HH:MM::SS
+            # Converts the date according to the specifications
             else if (date ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$/) {
                 gsub(/[-: ]/, "", date);
             }
             return date;
         }
         {
-        n = split(curs, arr, " ");
+        n = split(curs, arr, " "); # this is for specifying multiple currencies
         for (i = 1; i <= n; i++) {
-            cur[arr[i]] = 1
+            cur[arr[i]] = 1 # stored within map with some unimportant value (we seek whether key is present)
             }
         if(user==$1 && (!bfr || convdate(bfr) > convdate($2)) && (!afr || convdate(afr) < convdate($2)) && length($3) == 3){
             if(com=="list-currency") {
-                print $3
+                print $3 #lists currencies
                 } else if(com=="list") {
                     if($3 in cur || n==0) print
                 } else {
@@ -109,10 +120,10 @@ case "$COMMAND" in
             for(key in usr_cur){
                 printf "%s : %.4f\n", key, usr_cur[key] * (1+((com=="profit" && usr_cur[key] > 0)? (prof/100.0):0));
             }
-        }' | uniq | nl
+        }' | sort | uniq # sorts and makes entries unique
     ;;
     *)
-        echo "Error: Unknown command: $COMMAND" >&2
+        echo "Error: Unknown command: $COMMAND" >&2 # SANITY CHECK (COULDN'T BE TAKEN SERIOUS WITHOUT CAPS LOCK)
         exit 1
     ;;
 esac
